name = "Autocorrelations"
uuid = "b9118d5e-f165-4cbd-b2ae-b030566b7b26"
authors = ["Riccardo Foffi <riccardo.foffi@protonmail.com> and contributors"]
version = "0.1.1"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DSP = "0.7, 0.8"
Statistics = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
