name = "Autocovariances"
uuid = "b9118d5e-f165-4cbd-b2ae-b030566b7b26"
authors = ["Riccardo Foffi <riccardo.foffi@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
